// Generated by gencpp from file position_msgs/ObjectPosition.msg
// DO NOT EDIT!


#ifndef POSITION_MSGS_MESSAGE_OBJECTPOSITION_H
#define POSITION_MSGS_MESSAGE_OBJECTPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace position_msgs
{
template <class ContainerAllocator>
struct ObjectPosition_
{
  typedef ObjectPosition_<ContainerAllocator> Type;

  ObjectPosition_()
    : Class()
    , x(0)
    , y(0)
    , z(0)  {
    }
  ObjectPosition_(const ContainerAllocator& _alloc)
    : Class(_alloc)
    , x(0)
    , y(0)
    , z(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _Class_type;
  _Class_type Class;

   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::position_msgs::ObjectPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::position_msgs::ObjectPosition_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectPosition_

typedef ::position_msgs::ObjectPosition_<std::allocator<void> > ObjectPosition;

typedef boost::shared_ptr< ::position_msgs::ObjectPosition > ObjectPositionPtr;
typedef boost::shared_ptr< ::position_msgs::ObjectPosition const> ObjectPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::position_msgs::ObjectPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::position_msgs::ObjectPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::position_msgs::ObjectPosition_<ContainerAllocator1> & lhs, const ::position_msgs::ObjectPosition_<ContainerAllocator2> & rhs)
{
  return lhs.Class == rhs.Class &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::position_msgs::ObjectPosition_<ContainerAllocator1> & lhs, const ::position_msgs::ObjectPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace position_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::position_msgs::ObjectPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::position_msgs::ObjectPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::position_msgs::ObjectPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::position_msgs::ObjectPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::position_msgs::ObjectPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::position_msgs::ObjectPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::position_msgs::ObjectPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6475a486473154bd09397e55a585b9d4";
  }

  static const char* value(const ::position_msgs::ObjectPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6475a486473154bdULL;
  static const uint64_t static_value2 = 0x09397e55a585b9d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::position_msgs::ObjectPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "position_msgs/ObjectPosition";
  }

  static const char* value(const ::position_msgs::ObjectPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::position_msgs::ObjectPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Class\n"
"int64 x\n"
"int64 y\n"
"int64 z\n"
;
  }

  static const char* value(const ::position_msgs::ObjectPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::position_msgs::ObjectPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::position_msgs::ObjectPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::position_msgs::ObjectPosition_<ContainerAllocator>& v)
  {
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.Class);
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<int64_t>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSITION_MSGS_MESSAGE_OBJECTPOSITION_H
