// Generated by gencpp from file position_msgs/ObjectPositions.msg
// DO NOT EDIT!


#ifndef POSITION_MSGS_MESSAGE_OBJECTPOSITIONS_H
#define POSITION_MSGS_MESSAGE_OBJECTPOSITIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <position_msgs/ObjectPosition.h>

namespace position_msgs
{
template <class ContainerAllocator>
struct ObjectPositions_
{
  typedef ObjectPositions_<ContainerAllocator> Type;

  ObjectPositions_()
    : header()
    , object_positions()  {
    }
  ObjectPositions_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_positions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::position_msgs::ObjectPosition_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::position_msgs::ObjectPosition_<ContainerAllocator> >> _object_positions_type;
  _object_positions_type object_positions;





  typedef boost::shared_ptr< ::position_msgs::ObjectPositions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::position_msgs::ObjectPositions_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectPositions_

typedef ::position_msgs::ObjectPositions_<std::allocator<void> > ObjectPositions;

typedef boost::shared_ptr< ::position_msgs::ObjectPositions > ObjectPositionsPtr;
typedef boost::shared_ptr< ::position_msgs::ObjectPositions const> ObjectPositionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::position_msgs::ObjectPositions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::position_msgs::ObjectPositions_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::position_msgs::ObjectPositions_<ContainerAllocator1> & lhs, const ::position_msgs::ObjectPositions_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_positions == rhs.object_positions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::position_msgs::ObjectPositions_<ContainerAllocator1> & lhs, const ::position_msgs::ObjectPositions_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace position_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::position_msgs::ObjectPositions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::position_msgs::ObjectPositions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::position_msgs::ObjectPositions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::position_msgs::ObjectPositions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::position_msgs::ObjectPositions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::position_msgs::ObjectPositions_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::position_msgs::ObjectPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81cb5bcd0e3ca25231cb43df334f871f";
  }

  static const char* value(const ::position_msgs::ObjectPositions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81cb5bcd0e3ca252ULL;
  static const uint64_t static_value2 = 0x31cb43df334f871fULL;
};

template<class ContainerAllocator>
struct DataType< ::position_msgs::ObjectPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "position_msgs/ObjectPositions";
  }

  static const char* value(const ::position_msgs::ObjectPositions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::position_msgs::ObjectPositions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"ObjectPosition[] object_positions\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: position_msgs/ObjectPosition\n"
"string Class\n"
"int64 x\n"
"int64 y\n"
"int64 z\n"
;
  }

  static const char* value(const ::position_msgs::ObjectPositions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::position_msgs::ObjectPositions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_positions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectPositions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::position_msgs::ObjectPositions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::position_msgs::ObjectPositions_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object_positions[]" << std::endl;
    for (size_t i = 0; i < v.object_positions.size(); ++i)
    {
      s << indent << "  object_positions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::position_msgs::ObjectPosition_<ContainerAllocator> >::stream(s, indent + "    ", v.object_positions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSITION_MSGS_MESSAGE_OBJECTPOSITIONS_H
